export enum MarkdownNodeKind {
	Document = "Document",
	Paragraph = "Paragraph",
	BlockQuote = "BlockQuote",
	ListItem = "ListItem",
	List = "List",
	Header = "Header",
	CodeBlock = "CodeBlock",
	HorizontalRule = "HorizontalRule",
	Str = "Str",
	Emphasis = "Emphasis",
	Strong = "Strong",
	Html = "Html",
	Link = "Link",
	LinkReference = "LinkReference",
	Image = "Image",
	Code = "Code",
	Table = "Table",
	TableRow = "TableRow",
	TableCell = "TableCell"
}