name: Main Workflow

on: [push, pull_request]

jobs:
  run:
    name: Run

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-18.04]
        node: [8, 10, 13]

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}

      - name: Cache
        uses: actions/cache@preview
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node }}-node-

      - name: Setup pnpm
        run: npm install pnpm -g

      - name: Install
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm test
